// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rema1000ApiProject.Context;

namespace Rema1000ApiProject.Migrations
{
    [DbContext(typeof(Rema1000Context))]
    [Migration("20210516203727_attemptAtFinal")]
    partial class attemptAtFinal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rema1000ApiProject.Models.Address", b =>
                {
                    b.Property<Guid>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SupplierID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zipcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Rema1000ApiProject.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentCategoryCategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategoryCategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Rema1000ApiProject.Models.ContactPerson", b =>
                {
                    b.Property<Guid>("ContactPersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContactSupplierSupplierID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactPersonID");

                    b.HasIndex("ContactSupplierSupplierID");

                    b.ToTable("ContactPeople");
                });

            modelBuilder.Entity("Rema1000ApiProject.Models.MeasurementUnit", b =>
                {
                    b.Property<Guid>("MeasurementUnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MeasurementUnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MeasurementUnitID");

                    b.ToTable("MeasurementUnits");
                });

            modelBuilder.Entity("Rema1000ApiProject.Models.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GrossPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProductCategoryCategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductSupplierSupplierID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SalesPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UnitMeasurementUnitID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("ProductCategoryCategoryID");

                    b.HasIndex("ProductSupplierSupplierID");

                    b.HasIndex("UnitMeasurementUnitID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Rema1000ApiProject.Models.Supplier", b =>
                {
                    b.Property<Guid>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Rema1000ApiProject.Models.Address", b =>
                {
                    b.HasOne("Rema1000ApiProject.Models.Supplier", "Supplier")
                        .WithMany("SupplierAddresses")
                        .HasForeignKey("SupplierID");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Rema1000ApiProject.Models.Category", b =>
                {
                    b.HasOne("Rema1000ApiProject.Models.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryCategoryID");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Rema1000ApiProject.Models.ContactPerson", b =>
                {
                    b.HasOne("Rema1000ApiProject.Models.Supplier", "ContactSupplier")
                        .WithMany("SupplierContacts")
                        .HasForeignKey("ContactSupplierSupplierID");

                    b.Navigation("ContactSupplier");
                });

            modelBuilder.Entity("Rema1000ApiProject.Models.Product", b =>
                {
                    b.HasOne("Rema1000ApiProject.Models.Category", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryCategoryID");

                    b.HasOne("Rema1000ApiProject.Models.Supplier", "ProductSupplier")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("ProductSupplierSupplierID");

                    b.HasOne("Rema1000ApiProject.Models.MeasurementUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitMeasurementUnitID");

                    b.Navigation("ProductCategory");

                    b.Navigation("ProductSupplier");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Rema1000ApiProject.Models.Supplier", b =>
                {
                    b.Navigation("SupplierAddresses");

                    b.Navigation("SupplierContacts");

                    b.Navigation("SupplierProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
